spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;create=true
  jpa:
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: trace